name: bayesian_statistics_notes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - arviz>=0.7.0
  - bokeh
  - ipython>=7.13.0
  - joblib>=0.14.1
  - jupyterlab>=1.2.6
  - mathjax>=3.0.1
  - matplotlib>=3.1.3
  - notebook>=6.0.3
  - numba
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pip>=20.0.2
  - python>=3.8.3
  - pytorch>=1.5.0
  - scipy>=1.4.1
  - seaborn
  - tqdm>=4.46.0
  - xarray>=0.15.1
  - pip:
    - daft
    - future>=0.18.2
    - opt-einsum>=3.2.1
    - pyro-api>=0.1.2
    - pyro-ppl>=1.3.1

